import { extname, parse, join } from 'path';
import { getShimsForModule } from './requireConfig';
import {
    wrapTextModule,
    isNamedAMD,
    isAMDWithDefine,
    wrapShimmedModule,
    wrapNonShimmedModule,
    renameModule,
} from './transformAMD';
import { readFile } from './fsPromises';
import { MagentoRequireConfig } from './types';
import MagicString, { Bundle } from 'magic-string';
import { createRequireResolver } from './createRequireResolver';

/**
 * @summary Create a bundle file (compatible with the RequireJS runtime)
 *          from a collection of module IDs
 */
export async function createBundleFromDeps(
    bundleName: string,
    deps: string[],
    baseDir: string,
    requireConfig: MagentoRequireConfig,
) {
    const transformedModules = await Promise.all(
        deps.map(d => getFinalModuleSource(d, baseDir, requireConfig)),
    );
    const bundle = createBundle(transformedModules);
    bundle.append(`//# sourceMappingURL=${bundleName}.js.map`);
    const bundleFilename = `${parse(bundleName).name}.js`;
    const sourcemapFilename = `${bundleFilename}.map`;
    const sourcemap = bundle.generateMap({
        source: bundleFilename,
        file: sourcemapFilename,
        includeContent: true,
        hires: true,
    });

    return {
        bundleFilename,
        bundle: bundle.toString(),
        sourcemapFilename,
        sourcemap: sourcemap.toString(),
    };
}

/**
 * @todo Warn user when shim configs are found for a module
 *      that's already an AMD module
 */
async function getFinalModuleSource(
    dep: string,
    baseDir: string,
    requireConfig: MagentoRequireConfig,
) {
    const resolver = createRequireResolver(requireConfig);
    const path = join(baseDir, resolver(dep).modulePath);
    const source = await readFile(path, 'utf8');
    const isHTML = extname(path) === '.html';
    const shims = getShimsForModule(dep, requireConfig);
    const hasDefine = isAMDWithDefine(source);
    const isNamed = isNamedAMD(source);

    if (isHTML) {
        return { dep, file: wrapTextModule(dep, source) };
    }

    if (isNamed) {
        return { dep, file: new MagicString(source) };
    }

    if (!hasDefine) {
        if (shims) {
            return { dep, file: wrapShimmedModule(dep, source, shims) };
        }

        if (!shims) {
            return { dep, file: wrapNonShimmedModule(dep, source) };
        }
    }

    return { dep, file: renameModule(dep, source) };
}

function createBundle(modules: { dep: string; file: MagicString }[]) {
    const bundle = new Bundle();
    bundle.prepend(`/* Generated by @magento/baler - ${Date()} */\n\n`);
    for (const { dep, file } of modules) {
        bundle.addSource({
            filename: `../${dep}.js`,
            content: file,
        });
    }
    return bundle;
}
